using OpenIZ.OrmLite.Attributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace OpenIZ.Warehouse.ADO.Data.Model
{
    /// <summary>
    /// Message queue table
    /// </summary>
    [Table("msg_queue_tbl")]
    public class MessageQueueEntry
    {

        /// <summary>
        /// Message key
        /// </summary>
        [PrimaryKey, Column("msg_id"), NotNull, AutoGenerated]
        public Guid MessageKey { get; set; }

        /// <summary>
        /// Creation time
        /// </summary>
        [Column("crt_utc"), AutoGenerated, NotNull]
        public DateTime CreationTime { get; set; }

        /// <summary>
        /// Address
        /// </summary>
        [Column("to_addr"), NotNull]
        public String ToAddress { get; set; }

        /// <summary>
        /// Subject
        /// </summary>
        [Column("sub_txt"), NotNull]
        public String Subject { get; set; }

        /// <summary>
        /// Body
        /// </summary>
        [Column("body_txt"), NotNull]
        public String Body { get; set; }

        /// <summary>
        /// Time that the message should be scheduled
        /// </summary>
        [Column("schdl_utc"), NotNull, AutoGenerated]
        public DateTime? ScheduledTime { get; set; }

        /// <summary>
        /// Sent time
        /// </summary>
        [Column("sent_utc")]
        public DateTime? SentTime { get; set; }

        /// <summary>
        /// Status text of the object
        /// </summary>
        [Column("outc_cs")]
        public String StatusInfo { get; set; }


    }
}
